# fly.toml app configuration file generated for geography-of-technology on 2023-11-21T00:04:57-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "geography-of-technology"
primary_region = "cdg"

[build]

[env]
  ORIGIN = "https://geography-of-technology.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
